version: "3.7"
services:
  squid:
    image: xinux/squid-openssl
    container_name: my-squid
    restart: always
    ports:
      - 3127:3127
      - 3128:3128
      - 3129:3129
      - 3130:3130
    volumes:
      -  ./etc-squid:/etc/squid/
